"""initial_migration

Revision ID: 4c80d7909e9b
Revises: 
Create Date: 2022-05-23 23:03:28.279343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c80d7909e9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vartotojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Vartotojo vardas', sa.String(length=200), nullable=False),
    sa.Column('El paštas', sa.String(length=200), nullable=False),
    sa.Column('Slaptažodis', sa.String(length=200), nullable=False),
    sa.Column('Administratorius', sa.Boolean(), nullable=True),
    sa.Column('Darbuotojas', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Vartotojo vardas')
    )
    op.create_table('automobilis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Automobilio markė', sa.String(length=40), nullable=False),
    sa.Column('Automobilio modelis', sa.String(length=150), nullable=False),
    sa.Column('Pagaminimo metai', sa.String(length=50), nullable=False),
    sa.Column('Variklis', sa.String(), nullable=False),
    sa.Column('Valstybinis numeris', sa.String(length=8), nullable=False),
    sa.Column('VIN kodas', sa.String(length=30), nullable=False),
    sa.Column('vartotojo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vartotojo_id'], ['vartotojas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Valstybinis numeris')
    )
    op.create_table('irasas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sukurta', sa.DateTime(), nullable=True),
    sa.Column('Gedimas', sa.String(length=300), nullable=False),
    sa.Column('Kaina', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('vartotojas_id', sa.Integer(), nullable=True),
    sa.Column('automobilis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['automobilis_id'], ['automobilis.id'], ),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['vartotojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('irasas')
    op.drop_table('automobilis')
    op.drop_table('vartotojas')
    # ### end Alembic commands ###
