"""pirma

Revision ID: cbb34a9b7bf5
Revises: 4c80d7909e9b
Create Date: 2022-05-26 02:18:34.328754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb34a9b7bf5'
down_revision = '4c80d7909e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gedimai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Gedimo pavadinimas', sa.String(length=80), nullable=False),
    sa.Column('Remonto_kaina', sa.Integer(), nullable=False),
    sa.Column('Remonto statusas', sa.String(length=60), nullable=False),
    sa.Column('vartotojas_id', sa.Integer(), nullable=True),
    sa.Column('automobilis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['automobilis_id'], ['automobilis.id'], ),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['vartotojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('irasas', sa.Column('Suma', sa.Numeric(precision=16, scale=2), nullable=True))
    op.drop_constraint(None, 'irasas', type_='foreignkey')
    op.drop_column('irasas', 'Gedimas')
    op.drop_column('irasas', 'Kaina')
    op.drop_column('irasas', 'automobilis_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irasas', sa.Column('automobilis_id', sa.INTEGER(), nullable=True))
    op.add_column('irasas', sa.Column('Kaina', sa.NUMERIC(precision=16, scale=4), nullable=True))
    op.add_column('irasas', sa.Column('Gedimas', sa.VARCHAR(length=300), nullable=False))
    op.create_foreign_key(None, 'irasas', 'automobilis', ['automobilis_id'], ['id'])
    op.drop_column('irasas', 'Suma')
    op.drop_table('gedimai')
    # ### end Alembic commands ###
